#!/usr/bin/env -S deno run -A
// Agent tool adapters. `AGENTS.md` and `.agents/` are the single source for every agent
// tool; this script generates each tool's own files from them.
//
//   sync    write every adapter file
//   check   fail when an adapter file is missing or out of date (part of `pnpm run check`)
//
// Sources: AGENTS.md (instructions), .agents/skills/ (skills), .agents/mcp_config.json (MCP,
// Antigravity format), .agents/hooks/journal-context (session hook).
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HOOK = ".agents/hooks/journal-context";

type Json = Record<string, unknown>;
type Output =
  | { kind: "file"; path: string; content: string }
  | { kind: "symlink"; path: string; target: string }
  | { kind: "absent"; path: string; reason: string };

const read = function (path: string): string {
  return readFileSync(join(ROOT, path), "utf-8");
};

const json = function (value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
};

// Antigravity's mcp_config.json is the source; remote servers use `serverUrl` there.
const mcpServers = function (tool: "claude" | "cursor" | "gemini"): Json {
  const source = JSON.parse(read(".agents/mcp_config.json")) as {
    mcpServers?: Record<string, Json>;
  };
  const out: Json = {};
  for (const [name, server] of Object.entries(source.mcpServers ?? {})) {
    const { serverUrl, ...rest } = server;
    if (typeof serverUrl !== "string") {
      out[name] = rest;
      continue;
    }
    if (tool === "claude")
      out[name] = { type: "http", url: serverUrl, ...rest };
    if (tool === "cursor") out[name] = { url: serverUrl, ...rest };
    if (tool === "gemini") out[name] = { httpUrl: serverUrl, ...rest };
  }
  return out;
};

const claudeSettings = function (): string {
  const path = join(ROOT, ".claude/settings.json");
  const current = existsSync(path)
    ? (JSON.parse(read(".claude/settings.json")) as Json)
    : {};
  return json({
    ...current,
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume|clear|compact",
          hooks: [
            {
              type: "command",
              command: `\${CLAUDE_PROJECT_DIR}/${HOOK} claude`,
              timeout: 30,
            },
          ],
        },
      ],
    },
  });
};

const geminiSettings = function (): string {
  return json({
    context: { fileName: ["AGENTS.md"] },
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume|clear",
          hooks: [
            {
              type: "command",
              name: "journal-context",
              command: `$GEMINI_PROJECT_DIR/${HOOK} gemini`,
              timeout: 30000,
            },
          ],
        },
      ],
    },
    mcpServers: mcpServers("gemini"),
  });
};

const cursorHooks = function (): string {
  return json({
    version: 1,
    hooks: {
      sessionStart: [{ command: `${HOOK} cursor`, timeout: 30 }],
      preCompact: [{ command: `${HOOK} cursor pre-compact`, timeout: 30 }],
    },
  });
};

const ANTIGRAVITY_RULE = `---
trigger: always_on
---

# kuib — agent instructions

Read \`AGENTS.md\` at the repository root at the start of every session and follow it: it is
the single instruction source for this repository (@AGENTS.md). Skills live in
\`.agents/skills/\`.

<!-- Generated by scripts/agents.ts sync. Do not edit. -->
`;

const outputs = function (): Output[] {
  return [
    { kind: "file", path: "CLAUDE.md", content: "@AGENTS.md\n" },
    { kind: "symlink", path: ".claude/skills", target: "../.agents/skills" },
    { kind: "file", path: ".claude/settings.json", content: claudeSettings() },
    {
      kind: "file",
      path: ".mcp.json",
      content: json({ mcpServers: mcpServers("claude") }),
    },
    {
      kind: "file",
      path: ".cursor/mcp.json",
      content: json({ mcpServers: mcpServers("cursor") }),
    },
    { kind: "file", path: ".cursor/hooks.json", content: cursorHooks() },
    { kind: "file", path: ".gemini/settings.json", content: geminiSettings() },
    {
      kind: "file",
      path: ".agents/rules/agents.md",
      content: ANTIGRAVITY_RULE,
    },
    {
      kind: "absent",
      path: ".claude/rules",
      reason: "instructions come from AGENTS.md via CLAUDE.md",
    },
    { kind: "absent", path: ".claude/hooks", reason: `hooks run ${HOOK}` },
    { kind: "absent", path: ".cursor/hooks", reason: `hooks run ${HOOK}` },
    {
      kind: "absent",
      path: ".agents/rules/workflow.md",
      reason: "merged into AGENTS.md",
    },
    {
      kind: "absent",
      path: ".claude/templates",
      reason: "journal formats live in journal/SPEC.md",
    },
  ];
};

const exists = function (path: string): boolean {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
};

// Returns why the output is out of date, or null when it matches.
const problem = function (output: Output): string | null {
  const full = join(ROOT, output.path);
  if (output.kind === "absent") {
    return exists(full) ? `must not exist (${output.reason})` : null;
  }
  if (!exists(full)) return "missing";
  const stat = lstatSync(full);
  if (output.kind === "symlink") {
    if (!stat.isSymbolicLink()) return `must be a symlink to ${output.target}`;
    return readlinkSync(full) === output.target
      ? null
      : `must point at ${output.target}`;
  }
  if (stat.isSymbolicLink()) return "must be a regular file, not a symlink";
  return readFileSync(full, "utf-8") === output.content ? null : "out of date";
};

const skillProblems = function (): string[] {
  const out: string[] = [];
  const dir = join(ROOT, ".agents/skills");
  for (const name of readdirSync(dir).sort()) {
    const file = join(dir, name, "SKILL.md");
    if (!existsSync(file)) {
      out.push(`.agents/skills/${name}: missing SKILL.md`);
      continue;
    }
    const front =
      readFileSync(file, "utf-8").match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
    if (front.match(/^name:\s*(.+)$/m)?.[1].trim() !== name) {
      out.push(
        `.agents/skills/${name}/SKILL.md: name must equal the folder name`,
      );
    }
    if (!/^description:\s*\S/m.test(front)) {
      out.push(`.agents/skills/${name}/SKILL.md: missing description`);
    }
  }
  return out;
};

const write = function (output: Output) {
  const full = join(ROOT, output.path);
  if (output.kind === "absent") {
    rmSync(full, { recursive: true, force: true });
    return;
  }
  mkdirSync(dirname(full), { recursive: true });
  if (
    exists(full) &&
    (output.kind === "symlink" || lstatSync(full).isSymbolicLink())
  ) {
    rmSync(full, { recursive: true, force: true });
  }
  if (output.kind === "symlink") symlinkSync(output.target, full);
  else writeFileSync(full, output.content);
};

const command = process.argv[2];
if (command === "sync") {
  for (const output of outputs()) {
    if (problem(output) === null) continue;
    write(output);
    console.log(
      `  ${output.kind === "absent" ? "removed" : "wrote"} ${output.path}`,
    );
  }
  for (const issue of skillProblems()) console.log(`  [ERROR] ${issue}`);
} else if (command === "check") {
  const issues = outputs()
    .map(function (output) {
      const reason = problem(output);
      return reason ? `${output.path}: ${reason}` : null;
    })
    .filter(function (issue): issue is string {
      return issue !== null;
    })
    .concat(skillProblems());
  for (const issue of issues) console.log(`  [ERROR] ${issue}`);
  if (issues.length > 0) {
    console.log(`\n  ${issues.length} errors — run \`pnpm agents sync\``);
    process.exit(1);
  }
  console.log(
    `  agent adapters in sync (${relative(ROOT, join(ROOT, ".agents"))}/ → tools)`,
  );
} else {
  console.error("usage: agents.ts sync | check");
  process.exit(1);
}
